import { Goal, Transaction } from '../app/type/types';

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    title: 'Ăn trưa bạn bè',
    subtitle: 'Hôm nay',
    amount: -250000,
    date: '2024-05-30',
    icon: 'restaurant',
    colorClass: 'text-primary bg-primary/10',
    type: 'expense',
  },
  {
    id: '2',
    title: 'Lương tháng 5',
    subtitle: 'Hôm qua',
    amount: 15000000,
    date: '2024-05-29',
    icon: 'payments',
    colorClass: 'text-accent-green bg-accent-green/10',
    type: 'income',
  },
  {
    id: '3',
    title: 'Mua sắm online',
    subtitle: '28 Thg 5, 2024',
    amount: -1200000,
    date: '2024-05-28',
    icon: 'shopping_bag',
    colorClass: 'text-primary bg-primary/10',
    type: 'expense',
  },
  {
    id: '4',
    title: 'Cà phê Highland',
    subtitle: '25 Th10',
    amount: -55000,
    date: '2023-10-25',
    icon: 'coffee',
    colorClass: 'text-gray-700 bg-gray-100',
    type: 'expense',
  },
];

export const MOCK_GOALS: Goal[] = [
  {
    id: '1',
    title: 'Mua iPad',
    savedAmount: 6000000,
    targetAmount: 10000000,
    status: 'ongoing',
    deadline: '24 Thg 7, 2025',
    color: 'primary',
  },
  {
    id: '2',
    title: 'Quỹ khẩn cấp',
    savedAmount: 10000000,
    targetAmount: 10000000,
    status: 'completed',
    color: 'accent-green',
  },
  {
    id: '3',
    title: 'Mua iPhone mới',
    savedAmount: 5000000,
    targetAmount: 25000000,
    status: 'cancelled',
    deadline: '01 Thg 1, 2026',
    color: 'gray-400',
  },
];

export const ICONS = [
  {
    key: 'giaodich',
    label: 'Giao dịch',
    icons: [
      'payments',
      'account-balance-wallet',
      'savings',
      'currency-exchange',
      'point-of-sale',
    ],
  },
  {
    key: 'anUong',
    label: 'Ăn uống',
    icons: [
      'restaurant',
      'local-cafe',
      'local-bar',
      'cake',
      'fastfood',
    ],
  },
  {
    key: 'diChuyen',
    label: 'Di chuyển',
    icons: [
      'local-taxi',
      'directions-bus',
      'train',
      'tram',
      'flight',
      'local-gas-station',
      'directions-bike',
      'two-wheeler',
      'sailing',
      'car-repair',   
    ],
  },
  {
    key: 'giaDinh',
    label: 'Gia đình',
    icons: [
      'home',
      'child-care',
      'elderly',
      'pets',
      'favorite',
    ],
  },
  {
    key: 'giaiTri',
    label: 'Giải trí',
    icons: [
      'movie',
      'music-note',
      'sports-esports',
      'beach-access',
      'spa',
    ],
  },
  {
    key: 'hoaDon',
    label: 'Hóa đơn',
    icons: [
      'attach-money',
      'receipt',
      'home-repair-service',
      'account-balance',
      'local-phone',
      'wifi',
      'water-drop',
      'flash-on',
      'gas-meter',
    ],
  },
  {
    key: 'muaSam',
    label: 'Mua sắm',
    icons: [
      'local-grocery-store',
      'local-mall',
      'card-giftcard',
    ],
  },
  {
    key: 'sucKhoe',
    label: 'Sức khỏe',
    icons: [
      'fitness-center',
      'local-hospital',
      'spa',
      'self-improvement',
      'sports-soccer',
    ],
  },
  {
    key: 'giaoDuc',
    label: 'Giáo dục',
    icons: [
      'school',
    ],
  },
] as const;

export const COLORS = [
  '#F26060',
  '#F27660',
  '#F28C60',
  '#F2A260',
  '#F2B860',
  '#F2CD60',
  '#F2E360',
  '#EAF260',
  '#D5F260',
  '#BFF260',
  '#A9F260',
  '#93F260',
  '#7DF260',
  '#68F260',
  '#60F26F',
  '#60F285',
  '#60F29B',
  '#60F2B1',
  '#60F2C7',
  '#60F2DD',
  '#60EAF2',
  '#60D4F2',
  '#60BFF2',
  '#60A9F2',
  '#609BF2',
  '#6085F2',
  '#606FF2',
  '#6860F2',
  '#7D60F2',
  '#9360F2',
  '#A960F2',
  '#BF60F2',
  '#D560F2',
  '#EA60F2',
  '#F260E3',
  '#F260CD',
  '#F260B8',
  '#F260A2',
  '#F2608C',
  '#F26076',
];
